name: Automated Test & Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  regression:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build
          
  new-features:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so job can access it and uses the Node setup
        - uses: actions/checkout@v2
        - name: Use Nodejs 12.x
          uses: actions/setup-node@v1
          with:
            node-version: "12.x"
        # Install the CLI from NPM
        - name: Install the TestEngine-CLI
          run: | 
            npm install testengine-cli -g
        - name: Run TestEngine new feature tests
          env:
            TE_USER: ${{secrets.TESTENGINE_USER}}
          run: |
            testengine -u $TE_USER -p testengine -H http://54.202.9.115:8080/ run project ./
          
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Let them know your working
        run: echo Hi from publish!
          
          
          echo test, and deploy your project.
